// localization.ts - Comprehensive Natural Localization for English, Hindi, and Telugu

export type SupportedLanguage = 'en' | 'hi' | 'te';

export interface LanguageMeta {
  code: SupportedLanguage;
  label: string;
  nativeLabel: string;
  speechLocale: string;
  bcp47: string;
}

export const SUPPORTED_LANGUAGES: Record<SupportedLanguage, LanguageMeta> = {
  en: {
    code: 'en',
    label: 'English',
    nativeLabel: 'English',
    speechLocale: 'en-US',
    bcp47: 'en-US',
  },
  hi: {
    code: 'hi',
    label: 'Hindi',
    nativeLabel: 'हिन्दी',
    speechLocale: 'hi-IN',
    bcp47: 'hi-IN',
  },
  te: {
    code: 'te',
    label: 'Telugu',
    nativeLabel: 'తెలుగు',
    speechLocale: 'te-IN',
    bcp47: 'te-IN',
  },
};

export const UI_TRANSLATIONS = {
  en: {
    appName: 'SousVoice',
    appTagline: 'AI Kitchen Companion',
    heroBadge: 'Real-Time Voice AI • Hands-Free Cooking Companion',
    heroTitlePrefix: 'Turn',
    heroTitleAccent: 'Any Recipe',
    heroTitleSuffix: 'into an Interactive Voice Assistant',
    heroSubtitle:
      'Paste any recipe link or pick a dish. SousVoice extracts the steps, understands every ingredient, answers follow-up questions in real time with conversational memory, and lets you interrupt hands-free.',
    pastePlaceholder: 'Paste recipe or video URL (YouTube, Allrecipes, FoodNetwork...)',
    loadRecipe: 'Load Recipe',
    analyzingRecipe: 'Analyzing Recipe...',
    orQuickTest: 'Or Quick Test with a Pre-Extracted Dish:',
    howItWorks01Title: 'Paste Any URL',
    howItWorks01Desc: 'Accepts recipe links from any website with JSON-LD schema or structured tables.',
    howItWorks02Title: 'AI Understands',
    howItWorks02Desc: 'Extracts prep times, ingredient quantities, substitutions, and indexed cooking steps.',
    howItWorks03Title: 'Real-Time Voice',
    howItWorks03Desc: 'Instant spoken replies and active mic listening without touching your screen.',
    howItWorks04Title: 'Interrupt Anytime',
    howItWorks04Desc: 'Sub-millisecond generation-fenced barge-in cancels audio instantly and answers.',
    selectLanguage: 'Select Language',
    recipeReady: 'Recipe Ready',
    servings: 'Servings',
    cookTime: 'Cook',
    steps: 'Steps',
    whatYouCanAsk: 'What You Can Ask Hands-Free',
    interruptNotice: 'Interrupt anytime — stops audio instantly!',
    startCooking: 'Start Cooking',
    changeDish: '← Change Dish / URL',
    handsFreeNotice: 'Hands-free voice commands with instant interruption support.',
    switchDish: 'Switch',
    hideDetails: 'Hide Details',
    allSteps: 'All Steps',
    ingredients: 'Ingredients',
    stepProgress: 'Step',
    of: 'of',
    activeInstruction: 'Active Instruction',
    next: 'Next',
    previous: 'Previous',
    step: 'Step',
    duration: 'Duration',
    turns: 'Turns',
    bargeIns: 'Barge-ins',
    liveTranscript: 'Live Conversation Transcript',
    turnSingular: 'turn',
    turnPlural: 'turns',
    suggestedInquiries: 'Suggested Kitchen Inquiries (or speak naturally):',
    askPlaceholder: 'Ask any question about',
    askButton: 'Ask',
    micActive: 'Mic Active',
    micMuted: 'Mic Muted',
    endCooking: 'End Cooking',
    jumpToLatest: 'Jump to latest',
    askThisAgain: 'Ask this again',
    youSaidWait: 'You said wait',
    bargeInCutOff: 'Cut off (Barge-in)',
    queuedNext: 'Queued Next',
    cookingSessionComplete: 'Cooking Session Complete!',
    sessionCompleteDesc: 'Bon appétit! All voice interactions were successfully recorded.',
    backToHome: 'Select Another Dish / Recipe URL',
    restartRecipe: 'Restart This Recipe',
    settingsTitle: 'SousVoice Settings',
    displayTheme: 'Display Theme',
    darkKitchen: 'Dark Kitchen',
    daylight: 'Daylight',
    systemTheme: 'System',
    aiEnhancement: 'AI Enhancement (Optional)',
    aiEnhancementDesc: 'Add your OpenAI key for smarter, more personalized cooking answers. Saved locally in your browser.',
    done: 'Done',
    poweredBy: 'SousVoice AI',
    listeningHint: 'Speak naturally or interrupt anytime',
    hearingYou: 'Hearing You...',
    hearingYouSubtitle: 'Cook speaking hands-free',
    thinking: 'Thinking...',
    thinkingSubtitle: 'Processing your question',
    speaking: 'Speaking (Rime TTS)',
    speakingSubtitle: 'You can interrupt me anytime',
    interruptedTitle: 'Interrupted!',
    interruptedSubtitle: 'Barge-in detected — cancelling audio',
    voiceReady: 'Voice Ready',
    voiceReadySubtitle: 'Speak naturally or use text box',
    scaleNotice: 'Servings scaled to',
  },
  hi: {
    appName: 'सॉस-वॉइस (SousVoice)',
    appTagline: 'एआई किचन साथी',
    heroBadge: 'रीयल-टाइम वॉयस एआई • हैंड्स-फ्री कुकिंग साथी',
    heroTitlePrefix: 'बनाएं',
    heroTitleAccent: 'किसी भी रेसिपी को',
    heroTitleSuffix: 'एक इंटरैक्टिव वॉयस असिस्टेंट',
    heroSubtitle:
      'कोई भी रेसिपी लिंक पेस्ट करें या डिश चुनें। सॉस-वॉइस स्टेप्स समझता है, सामग्री का हिसाब रखता है, रीयल-टाइम में जवाब देता है, और बीच में टोकने पर तुरंत सुनता है।',
    pastePlaceholder: 'रेसिपी या वीडियो लिंक पेस्ट करें (YouTube, Allrecipes, आदि)...',
    loadRecipe: 'रेसिपी लोड करें',
    analyzingRecipe: 'रेसिपी समझ रहे हैं...',
    orQuickTest: 'या इनमें से कोई लोकप्रिय डिश चुनें:',
    howItWorks01Title: 'लिंक पेस्ट करें',
    howItWorks01Desc: 'किसी भी वेबसाइट या वीडियो से आसानी से रेसिपी निकालता है।',
    howItWorks02Title: 'एआई समझता है',
    howItWorks02Desc: 'पकाने का समय, सामग्री, और क्रमबद्ध स्टेप्स तैयार करता है।',
    howItWorks03Title: 'रीयल-टाइम आवाज़',
    howItWorks03Desc: 'स्क्रीन छुए बिना प्राकृतिक बातचीत और तुरंत जवाब।',
    howItWorks04Title: 'कभी भी रोकें',
    howItWorks04Desc: 'बोलते वक्त भी बीच में रोक सकते हैं, आवाज़ तुरंत बंद होकर नया जवाब मिलता है।',
    selectLanguage: 'भाषा चुनें (Select Language)',
    recipeReady: 'रेसिपी तैयार है',
    servings: 'लोग (Servings)',
    cookTime: 'पकाने का समय',
    steps: 'स्टेप्स',
    whatYouCanAsk: 'आप आवाज़ से क्या पूछ सकते हैं',
    interruptNotice: 'कभी भी बीच में रोकें — आवाज़ तुरंत बंद हो जाती है!',
    startCooking: 'पकाना शुरू करें (Start Cooking)',
    changeDish: '← दूसरी डिश या लिंक चुनें',
    handsFreeNotice: 'हैंड्स-फ्री वॉयस कमांड और तुरंत रुकने की सुविधा।',
    switchDish: 'बदलें',
    hideDetails: 'विवरण छुपाएं',
    allSteps: 'सभी स्टेप्स',
    ingredients: 'सामग्री (Ingredients)',
    stepProgress: 'स्टेप',
    of: 'का',
    activeInstruction: 'वर्तमान निर्देश',
    next: 'अगला',
    previous: 'पिछला',
    step: 'स्टेप',
    duration: 'समय',
    turns: 'बातचीत',
    bargeIns: 'रुकावटें',
    liveTranscript: 'लाइव बातचीत का विवरण',
    turnSingular: 'बारी',
    turnPlural: 'बारियां',
    suggestedInquiries: 'सुझाए गए सवाल (या सीधे अपनी आवाज़ में बोलें):',
    askPlaceholder: 'रेसिपी के बारे में कोई भी सवाल पूछें...',
    askButton: 'पूछें',
    micActive: 'माइक चालू है',
    micMuted: 'माइक बंद है',
    endCooking: 'कुकिंग समाप्त करें',
    jumpToLatest: 'ताज़ा बातचीत देखें',
    askThisAgain: 'यह फिर से पूछें',
    youSaidWait: 'आपने रुकने को कहा',
    bargeInCutOff: 'बीच में रोका गया',
    queuedNext: 'कतार में अगला',
    cookingSessionComplete: 'कुकिंग पूरी हुई!',
    sessionCompleteDesc: 'बहुत बढ़िया! आपकी कुकिंग का पूरा विवरण सुरक्षित है।',
    backToHome: 'दूसरी डिश चुनें',
    restartRecipe: 'यह रेसिपी फिर से शुरू करें',
    settingsTitle: 'सॉस-वॉइस सेटिंग्स',
    displayTheme: 'थीम',
    darkKitchen: 'डार्क किचन',
    daylight: 'डेलाइट',
    systemTheme: 'सिस्टम',
    aiEnhancement: 'एआई संवर्धन (वैकल्पिक)',
    aiEnhancementDesc: 'अधिक बुद्धिमान जवाबों के लिए अपनी OpenAI कुंजी जोड़ें। यह आपके ब्राउज़र में सुरक्षित रहती है।',
    done: 'हो गया',
    poweredBy: 'सॉस-वॉइस एआई',
    listeningHint: 'स्वाभाविक रूप से बोलें या कभी भी टोकें',
    hearingYou: 'सुन रहे हैं...',
    hearingYouSubtitle: 'आप बोल रहे हैं',
    thinking: 'सोच रहे हैं...',
    thinkingSubtitle: 'आपके सवाल का विश्लेषण हो रहा है',
    speaking: 'सॉस-वॉइस बोल रहा है',
    speakingSubtitle: 'आप मुझे कभी भी रोक सकते हैं',
    interruptedTitle: 'रोक दिया गया!',
    interruptedSubtitle: 'आवाज़ रोक दी गई है — नया सवाल सुन रहे हैं',
    voiceReady: 'आवाज़ तैयार है',
    voiceReadySubtitle: 'स्वाभाविक रूप से बोलें या टेक्स्ट बॉक्स का उपयोग करें',
    scaleNotice: 'मात्रा बदली गई',
  },
  te: {
    appName: 'సాస్‌వాయిస్ (SousVoice)',
    appTagline: 'ఏఐ వంట సహచరి',
    heroBadge: 'రియల్-టైమ్ వాయిస్ ఏఐ • చేతులు వాడకుండా వంట గైడ్',
    heroTitlePrefix: 'ఏ రెసిపీనైనా',
    heroTitleAccent: 'సులభంగా',
    heroTitleSuffix: 'ఇంటరాక్టివ్ వాయిస్ అసిస్టెంట్‌గా మార్చండి',
    heroSubtitle:
      'ఏదైనా రెసిపీ లింక్‌ను పేస్ట్ చేయండి లేదా వంటకాన్ని ఎంచుకోండి. సాస్‌వాయిస్ ప్రతి అడుగును అర్థం చేసుకుంటుంది, పదార్థాల కొలతలను ట్రాక్ చేస్తుంది మరియు చేతులు తాకకుండానే ప్రశ్నించే వెసులుబాటు ఇస్తుంది.',
    pastePlaceholder: 'రెసిపీ లేదా వీడియో లింక్ పేస్ట్ చేయండి (YouTube, Allrecipes మొదలైనవి)...',
    loadRecipe: 'రెసిపీని లోడ్ చేయండి',
    analyzingRecipe: 'రెసిపీని విశ్లేషిస్తోంది...',
    orQuickTest: 'లేదా ఈ ప్రముఖ వంటకాల్లో ఒకదాన్ని ఎంచుకోండి:',
    howItWorks01Title: 'లింక్ పేస్ట్ చేయండి',
    howItWorks01Desc: 'ఏ వెబ్‌సైట్ లేదా వీడియో నుండైనా రెసిపీని సులభంగా సేకరిస్తుంది.',
    howItWorks02Title: 'ఏఐ విశ్లేషణ',
    howItWorks02Desc: 'తయారీ సమయం, పదార్థాలు మరియు దశలను క్రమబద్ధీకరిస్తుంది.',
    howItWorks03Title: 'లైవ్ వాయిస్ సహాయం',
    howItWorks03Desc: 'స్క్రీన్‌ను తాకకుండా మాట్లాడి సూచనలు వినండి.',
    howItWorks04Title: 'ఎప్పుడైనా ఆపవచ్చు',
    howItWorks04Desc: 'మాట్లాడుతున్నప్పుడు మధ్యలోనే ఆపి కొత్త ప్రశ్న అడగవచ్చు.',
    selectLanguage: 'భాషను ఎంచుకోండి (Select Language)',
    recipeReady: 'రెసిపీ సిద్ధంగా ఉంది',
    servings: 'మందికి (Servings)',
    cookTime: 'వండే సమయం',
    steps: 'దశలు',
    whatYouCanAsk: 'మీరు అడగగలిగే సాధారణ ప్రశ్నలు',
    interruptNotice: 'మాట్లాడుతున్నప్పుడే ఆపవచ్చు — వెంటనే ఆగి మీ ప్రశ్న వింటుంది!',
    startCooking: 'వంట ప్రారంభించండి (Start Cooking)',
    changeDish: '← వేరే వంటకాన్ని ఎంచుకోండి',
    handsFreeNotice: 'చేతులు తాకకుండా వాయిస్ కమాండ్స్ మరియు తక్షణ రెస్పాన్స్.',
    switchDish: 'మార్చండి',
    hideDetails: 'వివరాలు దాచండి',
    allSteps: 'అన్ని దశలు',
    ingredients: 'కావలసిన పదార్థాలు (Ingredients)',
    stepProgress: 'దశ',
    of: 'లో',
    activeInstruction: 'ప్రస్తుత సూచన',
    next: 'తరువాత',
    previous: 'మునుపటి',
    step: 'దశ',
    duration: 'సమయం',
    turns: 'సంభాషణలు',
    bargeIns: 'మధ్యలో ఆపినవి',
    liveTranscript: 'లైవ్ సంభాషణ వివరాలు',
    turnSingular: 'సారి',
    turnPlural: 'సార్లు',
    suggestedInquiries: 'సూచించిన ప్రశ్నలు (లేదా నేరుగా మాట్లాడండి):',
    askPlaceholder: 'ఈ రెసిపీ గురించి ఏదైనా ప్రశ్న అడగండి...',
    askButton: 'అడగండి',
    micActive: 'మైక్ ఆన్‌లో ఉంది',
    micMuted: 'మైక్ మ్యూట్ చేయబడింది',
    endCooking: 'వంట ముగించండి',
    jumpToLatest: 'తాజా సంభాషణకు వెళ్లండి',
    askThisAgain: 'మళ్ళీ అడగండి',
    youSaidWait: 'మీరు ఆగమన్నారు',
    bargeInCutOff: 'మధ్యలో ఆపబడింది',
    queuedNext: 'తరువాతి ప్రశ్న',
    cookingSessionComplete: 'వంట పూర్తయింది!',
    sessionCompleteDesc: 'అభినందనలు! మీ వంట సంభాషణ వివరాలు భద్రపరచబడ్డాయి.',
    backToHome: 'మరొక వంటకాన్ని ఎంచుకోండి',
    restartRecipe: 'ఈ రెసిపీని మళ్లీ ప్రారంభించండి',
    settingsTitle: 'సాస్‌వాయిస్ సెట్టింగ్‌లు',
    displayTheme: 'థీమ్',
    darkKitchen: 'డార్క్ కిచెన్',
    daylight: 'డేలైట్',
    systemTheme: 'సిస్టమ్',
    aiEnhancement: 'ఏఐ మెరుగుదల (ఐచ్ఛికం)',
    aiEnhancementDesc: 'మరింత తెలివైన సమాధానాల కోసం మీ OpenAI కీని జోడించండి. ఇది మీ బ్రౌజర్‌లో సురక్షితంగా ఉంటుంది.',
    done: 'పూర్తయింది',
    poweredBy: 'సాస్‌వాయిస్ ఏఐ',
    listeningHint: 'సహజంగా మాట్లాడండి లేదా మధ్యలో ఆపండి',
    hearingYou: 'వింటున్నాము...',
    hearingYouSubtitle: 'మీరు మాట్లాడుతున్నారు',
    thinking: 'ఆలోచిస్తున్నాము...',
    thinkingSubtitle: 'సమాధానం సిద్ధం చేస్తోంది',
    speaking: 'సాస్‌వాయిస్ మాట్లాడుతోంది',
    speakingSubtitle: 'మీరు నన్ను ఎప్పుడైనా ఆపవచ్చు',
    interruptedTitle: 'ఆపబడింది!',
    interruptedSubtitle: 'కొత్త ప్రశ్న వినడానికి సిద్ధంగా ఉంది',
    voiceReady: 'వాయిస్ సిద్ధం',
    voiceReadySubtitle: 'సహజంగా మాట్లాడండి లేదా టైప్ చేయండి',
    scaleNotice: 'కొలతలు మార్చబడ్డాయి',
  },
};

export function getTranslation(lang: SupportedLanguage = 'en') {
  return UI_TRANSLATIONS[lang] || UI_TRANSLATIONS.en;
}
